apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: default
type: Opaque
data:
  # Redis
  REDIS_HOST: cmVkaXM=      # "redis" → dev replace với host thật nếu cần
  REDIS_PORT: NjM3OQ==      # "6379"

  # Kafka
  KAFKA_BROKER: a2VtY2hhLmNvbTo5MDky # placeholder, replace với broker thật

  # JWT secret
  JWT_SECRET: c2VjcmV0X3Rlc3Q=  # "secret_test" → replace với key thật

  # Database
  DB_USER: dXNlcg==           # "user"
  DB_PASS: cGFzc3dvcmQ=       # "password"
  DB_HOST: bG9jYWxob3N0       # "localhost"
  DB_PORT: NTQzMg==           # "5432"
