export const AUTH = {
  VERIFICATION_TOKEN_DAYS: 3,
  RESET_TOKEN_HOURS: 2,
  EMAIL_VERIFICATION_TIMEOUT_DAYS: 7,
  JWT_SECRET: process.env.JWT_SECRET || 'my-secret',
  PASSWORD_RESET_TIMEOUT_HOURS: 24
}
