"""init tables

Revision ID: 3e47178acc44
Revises:
Create Date: 2025-07-09 15:46:43.405158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3e47178acc44"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum("FILE", "TEXT", "URL", name="documenttypeenum"),
            nullable=True,
        ),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("HIGH", "MEDIUM", "LOW", "NONE", name="priorityenum"),
            nullable=True,
        ),
        sa.Column(
            "training_status",
            sa.Enum("UNTRAINED", "PENDING", "TRAINED", name="trainingstatusenum"),
            nullable=True,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=True),
        sa.Column("url_title", sa.String(length=255), nullable=True),
        sa.Column("url_description", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("uploader_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization_training_status",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("is_training", sa.Boolean(), nullable=True),
        sa.Column("training_started_at", sa.DateTime(), nullable=True),
        sa.Column("training_completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id"),
    )
    # op.drop_index(op.f('OrganizationMember_userId_organizationId_key'), table_name='OrganizationMember')
    # op.drop_table('OrganizationMember')
    # op.drop_index(op.f('OrganizationInvite_inviteCode_key'), table_name='OrganizationInvite')
    # op.drop_table('OrganizationInvite')
    # op.drop_index(op.f('PasswordResetTokens_token_key'), table_name='PasswordResetTokens')
    # op.drop_index(op.f('PasswordResetTokens_userId_idx'), table_name='PasswordResetTokens')
    # op.drop_table('PasswordResetTokens')
    # op.drop_table('organization_subscriptions')
    # op.drop_index(op.f('Organization_contactEmail_key'), table_name='Organization')
    # op.drop_table('Organization')
    # op.drop_index(op.f('User_email_key'), table_name='User')
    # op.drop_table('User')
    # op.drop_index(op.f('EmailVerificationTokens_token_key'), table_name='EmailVerificationTokens')
    # op.drop_index(op.f('EmailVerificationTokens_userId_idx'), table_name='EmailVerificationTokens')
    # op.drop_table('EmailVerificationTokens')
    # op.drop_table('subscription_tiers')
    # op.drop_table('_prisma_migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('_prisma_migrations',
    # sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    # sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    # sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    # )
    # op.create_table('subscription_tiers',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    # sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('price_monthly', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    # sa.Column('price_yearly', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    # sa.Column('storage_limit_mb', sa.BIGINT(), server_default=sa.text('100'), autoincrement=False, nullable=True),
    # sa.Column('ai_queries_limit', sa.BIGINT(), server_default=sa.text('500'), autoincrement=False, nullable=True),
    # sa.Column('human_agents_limit', sa.BIGINT(), server_default=sa.text('2'), autoincrement=False, nullable=True),
    # sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='subscription_tiers_pkey'),
    # sa.UniqueConstraint('name', name='uni_subscription_tiers_name'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('EmailVerificationTokens',
    # sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('isUsed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    # sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('EmailVerificationTokens_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name=op.f('EmailVerificationTokens_pkey'))
    # )
    # op.create_index(op.f('EmailVerificationTokens_userId_idx'), 'EmailVerificationTokens', ['userId'], unique=False)
    # op.create_index(op.f('EmailVerificationTokens_token_key'), 'EmailVerificationTokens', ['token'], unique=True)
    # op.create_table('User',
    # sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    # sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    # sa.Column('avatar', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='User_pkey'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    # op.create_table('Organization',
    # sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('logo', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('contactEmail', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('contactPhone', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.Column('billingEmail', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('billingAddress', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('knowledgeDatabaseUrl', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('knowledgeDatabaseNamespace', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='Organization_pkey'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_index(op.f('Organization_contactEmail_key'), 'Organization', ['contactEmail'], unique=True)
    # op.create_table('organization_subscriptions',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('tier_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    # sa.Column('billing_period', sa.VARCHAR(length=10), server_default=sa.text("'MONTHLY'::character varying"), autoincrement=False, nullable=True),
    # sa.Column('current_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('current_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('storage_used_mb', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    # sa.Column('ai_queries_used', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    # sa.Column('auto_renew', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    # sa.Column('cancel_at_period_end', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    # sa.Column('additional_storage_mb', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    # sa.Column('additional_ai_queries', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    # sa.Column('additional_agents', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['tier_id'], ['subscription_tiers.id'], name=op.f('fk_organization_subscriptions_tier')),
    # sa.PrimaryKeyConstraint('id', name=op.f('organization_subscriptions_pkey'))
    # )
    # op.create_table('PasswordResetTokens',
    # sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('isUsed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    # sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('PasswordResetTokens_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name=op.f('PasswordResetTokens_pkey'))
    # )
    # op.create_index(op.f('PasswordResetTokens_userId_idx'), 'PasswordResetTokens', ['userId'], unique=False)
    # op.create_index(op.f('PasswordResetTokens_token_key'), 'PasswordResetTokens', ['token'], unique=True)
    # op.create_table('OrganizationInvite',
    # sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('organizationId', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'AGENT', name='MemberRole'), autoincrement=False, nullable=False),
    # sa.Column('invitedById', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('inviteCode', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    # sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    # sa.Column('isUsed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    # sa.Column('isRevoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['invitedById'], ['User.id'], name=op.f('OrganizationInvite_invitedById_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], name=op.f('OrganizationInvite_organizationId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name=op.f('OrganizationInvite_pkey'))
    # )
    # op.create_index(op.f('OrganizationInvite_inviteCode_key'), 'OrganizationInvite', ['inviteCode'], unique=True)
    # op.create_table('OrganizationMember',
    # sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'AGENT', name='MemberRole'), autoincrement=False, nullable=False),
    # sa.Column('joinedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('organizationId', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], name=op.f('OrganizationMember_organizationId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('OrganizationMember_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE')
    # )
    # op.create_index(op.f('OrganizationMember_userId_organizationId_key'), 'OrganizationMember', ['userId', 'organizationId'], unique=True)
    op.drop_table("organization_training_status")
    op.drop_table("documents")
    # ### end Alembic commands ###
