"""add s3 key to CoolDocument

Revision ID: 6e42b2d8d2a3
Revises: 3e47178acc44
Create Date: 2025-07-13 14:05:08.190854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6e42b2d8d2a3"
down_revision: Union[str, Sequence[str], None] = "3e47178acc44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("s3_key", sa.String(length=2000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "s3_key")
    # ### end Alembic commands ###
