"""Use func.now() for timestamps

Revision ID: cc4e79db4af4
Revises: 6fbaa0d5ae7b
Create Date: 2025-07-14 14:27:20.447858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc4e79db4af4'
down_revision: Union[str, Sequence[str], None] = '6fbaa0d5ae7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 's3_key',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 's3_key',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###
