"""add url_expires_at to documents

Revision ID: f50f3907fe9e
Revises: 6e42b2d8d2a3
Create Date: 2025-07-13 17:57:24.127587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f50f3907fe9e"
down_revision: Union[str, Sequence[str], None] = "6e42b2d8d2a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("url_expires_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "url_expires_at")

    # ### end Alembic commands ###
