// Đây là file định nghĩa giao diện (interface) của dịch vụ CHAT theo định dạng Protocol Buffers
//(proto3). File này định nghĩa các message truyền tải dữ liệu giữa client và server cũng như
//service với phương thức RPC.
//protoc --go_out=. --go-grpc_out=. proto/chat/chat.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/chat/chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDailyChatSummaryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	DateExact      string                 `protobuf:"bytes,2,opt,name=date_exact,json=dateExact,proto3" json:"date_exact,omitempty"` // YYYY-MM-DD format
	DateGte        string                 `protobuf:"bytes,3,opt,name=date_gte,json=dateGte,proto3" json:"date_gte,omitempty"`       // YYYY-MM-DD format
	DateLte        string                 `protobuf:"bytes,4,opt,name=date_lte,json=dateLte,proto3" json:"date_lte,omitempty"`       // YYYY-MM-DD format
	Ordering       string                 `protobuf:"bytes,5,opt,name=ordering,proto3" json:"ordering,omitempty"`                    // default: "-date"
	Page           int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`                           // default: 1
	PageSize       int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // default: 20
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDailyChatSummaryRequest) Reset() {
	*x = GetDailyChatSummaryRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyChatSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyChatSummaryRequest) ProtoMessage() {}

func (x *GetDailyChatSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyChatSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetDailyChatSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *GetDailyChatSummaryRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetDailyChatSummaryRequest) GetDateExact() string {
	if x != nil {
		return x.DateExact
	}
	return ""
}

func (x *GetDailyChatSummaryRequest) GetDateGte() string {
	if x != nil {
		return x.DateGte
	}
	return ""
}

func (x *GetDailyChatSummaryRequest) GetDateLte() string {
	if x != nil {
		return x.DateLte
	}
	return ""
}

func (x *GetDailyChatSummaryRequest) GetOrdering() string {
	if x != nil {
		return x.Ordering
	}
	return ""
}

func (x *GetDailyChatSummaryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDailyChatSummaryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetDailyChatSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Next          string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previos       string                 `protobuf:"bytes,3,opt,name=previos,proto3" json:"previos,omitempty"`
	Results       []*DailyChatSummary    `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyChatSummaryResponse) Reset() {
	*x = GetDailyChatSummaryResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyChatSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyChatSummaryResponse) ProtoMessage() {}

func (x *GetDailyChatSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyChatSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetDailyChatSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *GetDailyChatSummaryResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetDailyChatSummaryResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *GetDailyChatSummaryResponse) GetPrevios() string {
	if x != nil {
		return x.Previos
	}
	return ""
}

func (x *GetDailyChatSummaryResponse) GetResults() []*DailyChatSummary {
	if x != nil {
		return x.Results
	}
	return nil
}

type DailyChatSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Date           string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD format
	// Conversation metrics (by conversation creation date)
	TotalConversations             int32   `protobuf:"varint,3,opt,name=total_conversations,json=totalConversations,proto3" json:"total_conversations,omitempty"`
	AiConversations                int32   `protobuf:"varint,4,opt,name=ai_conversations,json=aiConversations,proto3" json:"ai_conversations,omitempty"`
	HumanConversations             int32   `protobuf:"varint,5,opt,name=human_conversations,json=humanConversations,proto3" json:"human_conversations,omitempty"`
	AvgConversationDurationMinutes float64 `protobuf:"fixed64,6,opt,name=avg_conversation_duration_minutes,json=avgConversationDurationMinutes,proto3" json:"avg_conversation_duration_minutes,omitempty"`
	// Message metrics (by message sending date)
	TotalMessages    int32 `protobuf:"varint,7,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	CustomerMessages int32 `protobuf:"varint,8,opt,name=customer_messages,json=customerMessages,proto3" json:"customer_messages,omitempty"`
	AgentMessages    int32 `protobuf:"varint,9,opt,name=agent_messages,json=agentMessages,proto3" json:"agent_messages,omitempty"`
	AiMessages       int32 `protobuf:"varint,10,opt,name=ai_messages,json=aiMessages,proto3" json:"ai_messages,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DailyChatSummary) Reset() {
	*x = DailyChatSummary{}
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyChatSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyChatSummary) ProtoMessage() {}

func (x *DailyChatSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyChatSummary.ProtoReflect.Descriptor instead.
func (*DailyChatSummary) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *DailyChatSummary) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DailyChatSummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyChatSummary) GetTotalConversations() int32 {
	if x != nil {
		return x.TotalConversations
	}
	return 0
}

func (x *DailyChatSummary) GetAiConversations() int32 {
	if x != nil {
		return x.AiConversations
	}
	return 0
}

func (x *DailyChatSummary) GetHumanConversations() int32 {
	if x != nil {
		return x.HumanConversations
	}
	return 0
}

func (x *DailyChatSummary) GetAvgConversationDurationMinutes() float64 {
	if x != nil {
		return x.AvgConversationDurationMinutes
	}
	return 0
}

func (x *DailyChatSummary) GetTotalMessages() int32 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *DailyChatSummary) GetCustomerMessages() int32 {
	if x != nil {
		return x.CustomerMessages
	}
	return 0
}

func (x *DailyChatSummary) GetAgentMessages() int32 {
	if x != nil {
		return x.AgentMessages
	}
	return 0
}

func (x *DailyChatSummary) GetAiMessages() int32 {
	if x != nil {
		return x.AiMessages
	}
	return 0
}

type GetAllTimeStatsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAllTimeStatsRequest) Reset() {
	*x = GetAllTimeStatsRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTimeStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTimeStatsRequest) ProtoMessage() {}

func (x *GetAllTimeStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTimeStatsRequest.ProtoReflect.Descriptor instead.
func (*GetAllTimeStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllTimeStatsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetAllTimeStatsResponse struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	TotalConversations             int32                  `protobuf:"varint,1,opt,name=total_conversations,json=totalConversations,proto3" json:"total_conversations,omitempty"`
	AiConversations                int32                  `protobuf:"varint,2,opt,name=ai_conversations,json=aiConversations,proto3" json:"ai_conversations,omitempty"`
	HumanConversations             int32                  `protobuf:"varint,3,opt,name=human_conversations,json=humanConversations,proto3" json:"human_conversations,omitempty"`
	TotalMessages                  int32                  `protobuf:"varint,4,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	CustomerMessages               int32                  `protobuf:"varint,5,opt,name=customer_messages,json=customerMessages,proto3" json:"customer_messages,omitempty"`
	AgentMessages                  int32                  `protobuf:"varint,6,opt,name=agent_messages,json=agentMessages,proto3" json:"agent_messages,omitempty"`
	AiMessages                     int32                  `protobuf:"varint,7,opt,name=ai_messages,json=aiMessages,proto3" json:"ai_messages,omitempty"`
	AvgMessagesPerConversation     float64                `protobuf:"fixed64,8,opt,name=avg_messages_per_conversation,json=avgMessagesPerConversation,proto3" json:"avg_messages_per_conversation,omitempty"`
	AvgConversationDurationMinutes float64                `protobuf:"fixed64,9,opt,name=avg_conversation_duration_minutes,json=avgConversationDurationMinutes,proto3" json:"avg_conversation_duration_minutes,omitempty"`
	FirstConversationDate          string                 `protobuf:"bytes,10,opt,name=first_conversation_date,json=firstConversationDate,proto3" json:"first_conversation_date,omitempty"` // "YYYY-MM-DD"
	LastConversationDate           string                 `protobuf:"bytes,11,opt,name=last_conversation_date,json=lastConversationDate,proto3" json:"last_conversation_date,omitempty"`
	BusiestDay                     string                 `protobuf:"bytes,12,opt,name=busiest_day,json=busiestDay,proto3" json:"busiest_day,omitempty"`
	BusiestDayConversationCount    int32                  `protobuf:"varint,13,opt,name=busiest_day_conversation_count,json=busiestDayConversationCount,proto3" json:"busiest_day_conversation_count,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GetAllTimeStatsResponse) Reset() {
	*x = GetAllTimeStatsResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTimeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTimeStatsResponse) ProtoMessage() {}

func (x *GetAllTimeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTimeStatsResponse.ProtoReflect.Descriptor instead.
func (*GetAllTimeStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllTimeStatsResponse) GetTotalConversations() int32 {
	if x != nil {
		return x.TotalConversations
	}
	return 0
}

func (x *GetAllTimeStatsResponse) GetAiConversations() int32 {
	if x != nil {
		return x.AiConversations
	}
	return 0
}

func (x *GetAllTimeStatsResponse) GetHumanConversations() int32 {
	if x != nil {
		return x.HumanConversations
	}
	return 0
}

func (x *GetAllTimeStatsResponse) GetTotalMessages() int32 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *GetAllTimeStatsResponse) GetCustomerMessages() int32 {
	if x != nil {
		return x.CustomerMessages
	}
	return 0
}

func (x *GetAllTimeStatsResponse) GetAgentMessages() int32 {
	if x != nil {
		return x.AgentMessages
	}
	return 0
}

func (x *GetAllTimeStatsResponse) GetAiMessages() int32 {
	if x != nil {
		return x.AiMessages
	}
	return 0
}

func (x *GetAllTimeStatsResponse) GetAvgMessagesPerConversation() float64 {
	if x != nil {
		return x.AvgMessagesPerConversation
	}
	return 0
}

func (x *GetAllTimeStatsResponse) GetAvgConversationDurationMinutes() float64 {
	if x != nil {
		return x.AvgConversationDurationMinutes
	}
	return 0
}

func (x *GetAllTimeStatsResponse) GetFirstConversationDate() string {
	if x != nil {
		return x.FirstConversationDate
	}
	return ""
}

func (x *GetAllTimeStatsResponse) GetLastConversationDate() string {
	if x != nil {
		return x.LastConversationDate
	}
	return ""
}

func (x *GetAllTimeStatsResponse) GetBusiestDay() string {
	if x != nil {
		return x.BusiestDay
	}
	return ""
}

func (x *GetAllTimeStatsResponse) GetBusiestDayConversationCount() int32 {
	if x != nil {
		return x.BusiestDayConversationCount
	}
	return 0
}

var File_proto_chat_chat_proto protoreflect.FileDescriptor

const file_proto_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x15proto/chat/chat.proto\x12\x04chat\"\xe7\x01\n" +
	"\x1aGetDailyChatSummaryRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"date_exact\x18\x02 \x01(\tR\tdateExact\x12\x19\n" +
	"\bdate_gte\x18\x03 \x01(\tR\adateGte\x12\x19\n" +
	"\bdate_lte\x18\x04 \x01(\tR\adateLte\x12\x1a\n" +
	"\bordering\x18\x05 \x01(\tR\bordering\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"\x93\x01\n" +
	"\x1bGetDailyChatSummaryResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x18\n" +
	"\aprevios\x18\x03 \x01(\tR\aprevios\x120\n" +
	"\aresults\x18\x04 \x03(\v2\x16.chat.DailyChatSummaryR\aresults\"\xc3\x03\n" +
	"\x10DailyChatSummary\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12/\n" +
	"\x13total_conversations\x18\x03 \x01(\x05R\x12totalConversations\x12)\n" +
	"\x10ai_conversations\x18\x04 \x01(\x05R\x0faiConversations\x12/\n" +
	"\x13human_conversations\x18\x05 \x01(\x05R\x12humanConversations\x12I\n" +
	"!avg_conversation_duration_minutes\x18\x06 \x01(\x01R\x1eavgConversationDurationMinutes\x12%\n" +
	"\x0etotal_messages\x18\a \x01(\x05R\rtotalMessages\x12+\n" +
	"\x11customer_messages\x18\b \x01(\x05R\x10customerMessages\x12%\n" +
	"\x0eagent_messages\x18\t \x01(\x05R\ragentMessages\x12\x1f\n" +
	"\vai_messages\x18\n" +
	" \x01(\x05R\n" +
	"aiMessages\"A\n" +
	"\x16GetAllTimeStatsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"\xa4\x05\n" +
	"\x17GetAllTimeStatsResponse\x12/\n" +
	"\x13total_conversations\x18\x01 \x01(\x05R\x12totalConversations\x12)\n" +
	"\x10ai_conversations\x18\x02 \x01(\x05R\x0faiConversations\x12/\n" +
	"\x13human_conversations\x18\x03 \x01(\x05R\x12humanConversations\x12%\n" +
	"\x0etotal_messages\x18\x04 \x01(\x05R\rtotalMessages\x12+\n" +
	"\x11customer_messages\x18\x05 \x01(\x05R\x10customerMessages\x12%\n" +
	"\x0eagent_messages\x18\x06 \x01(\x05R\ragentMessages\x12\x1f\n" +
	"\vai_messages\x18\a \x01(\x05R\n" +
	"aiMessages\x12A\n" +
	"\x1davg_messages_per_conversation\x18\b \x01(\x01R\x1aavgMessagesPerConversation\x12I\n" +
	"!avg_conversation_duration_minutes\x18\t \x01(\x01R\x1eavgConversationDurationMinutes\x126\n" +
	"\x17first_conversation_date\x18\n" +
	" \x01(\tR\x15firstConversationDate\x124\n" +
	"\x16last_conversation_date\x18\v \x01(\tR\x14lastConversationDate\x12\x1f\n" +
	"\vbusiest_day\x18\f \x01(\tR\n" +
	"busiestDay\x12C\n" +
	"\x1ebusiest_day_conversation_count\x18\r \x01(\x05R\x1bbusiestDayConversationCount2\xbb\x01\n" +
	"\vChatService\x12\\\n" +
	"\x13GetDailyChatSummary\x12 .chat.GetDailyChatSummaryRequest\x1a!.chat.GetDailyChatSummaryResponse\"\x00\x12N\n" +
	"\x0fGetAllTimeStats\x12\x1c.chat.GetAllTimeStatsRequest\x1a\x1d.chat.GetAllTimeStatsResponseB\fZ\n" +
	"proto/chatb\x06proto3"

var (
	file_proto_chat_chat_proto_rawDescOnce sync.Once
	file_proto_chat_chat_proto_rawDescData []byte
)

func file_proto_chat_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)))
	})
	return file_proto_chat_chat_proto_rawDescData
}

var file_proto_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_chat_chat_proto_goTypes = []any{
	(*GetDailyChatSummaryRequest)(nil),  // 0: chat.GetDailyChatSummaryRequest
	(*GetDailyChatSummaryResponse)(nil), // 1: chat.GetDailyChatSummaryResponse
	(*DailyChatSummary)(nil),            // 2: chat.DailyChatSummary
	(*GetAllTimeStatsRequest)(nil),      // 3: chat.GetAllTimeStatsRequest
	(*GetAllTimeStatsResponse)(nil),     // 4: chat.GetAllTimeStatsResponse
}
var file_proto_chat_chat_proto_depIdxs = []int32{
	2, // 0: chat.GetDailyChatSummaryResponse.results:type_name -> chat.DailyChatSummary
	0, // 1: chat.ChatService.GetDailyChatSummary:input_type -> chat.GetDailyChatSummaryRequest
	3, // 2: chat.ChatService.GetAllTimeStats:input_type -> chat.GetAllTimeStatsRequest
	1, // 3: chat.ChatService.GetDailyChatSummary:output_type -> chat.GetDailyChatSummaryResponse
	4, // 4: chat.ChatService.GetAllTimeStats:output_type -> chat.GetAllTimeStatsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_chat_chat_proto_init() }
func file_proto_chat_chat_proto_init() {
	if File_proto_chat_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_chat_proto = out.File
	file_proto_chat_chat_proto_goTypes = nil
	file_proto_chat_chat_proto_depIdxs = nil
}
