// Đây là file định nghĩa giao diện (interface) của dịch vụ CHAT theo định dạng Protocol Buffers
//(proto3). File này định nghĩa các message truyền tải dữ liệu giữa client và server cũng như
//service với phương thức RPC.
//protoc --go_out=. --go-grpc_out=. proto/chat/chat.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/chat/chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_GetDailyChatSummary_FullMethodName = "/chat.ChatService/GetDailyChatSummary"
	ChatService_GetAllTimeStats_FullMethodName     = "/chat.ChatService/GetAllTimeStats"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	// Một ví dụ đơn giản về RPC kiểu unary (client gửi 1 request và nhận 1 response)
	GetDailyChatSummary(ctx context.Context, in *GetDailyChatSummaryRequest, opts ...grpc.CallOption) (*GetDailyChatSummaryResponse, error)
	GetAllTimeStats(ctx context.Context, in *GetAllTimeStatsRequest, opts ...grpc.CallOption) (*GetAllTimeStatsResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) GetDailyChatSummary(ctx context.Context, in *GetDailyChatSummaryRequest, opts ...grpc.CallOption) (*GetDailyChatSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyChatSummaryResponse)
	err := c.cc.Invoke(ctx, ChatService_GetDailyChatSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetAllTimeStats(ctx context.Context, in *GetAllTimeStatsRequest, opts ...grpc.CallOption) (*GetAllTimeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTimeStatsResponse)
	err := c.cc.Invoke(ctx, ChatService_GetAllTimeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
type ChatServiceServer interface {
	// Một ví dụ đơn giản về RPC kiểu unary (client gửi 1 request và nhận 1 response)
	GetDailyChatSummary(context.Context, *GetDailyChatSummaryRequest) (*GetDailyChatSummaryResponse, error)
	GetAllTimeStats(context.Context, *GetAllTimeStatsRequest) (*GetAllTimeStatsResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) GetDailyChatSummary(context.Context, *GetDailyChatSummaryRequest) (*GetDailyChatSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyChatSummary not implemented")
}
func (UnimplementedChatServiceServer) GetAllTimeStats(context.Context, *GetAllTimeStatsRequest) (*GetAllTimeStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTimeStats not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_GetDailyChatSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyChatSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetDailyChatSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetDailyChatSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetDailyChatSummary(ctx, req.(*GetDailyChatSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetAllTimeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTimeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetAllTimeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetAllTimeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetAllTimeStats(ctx, req.(*GetAllTimeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailyChatSummary",
			Handler:    _ChatService_GetDailyChatSummary_Handler,
		},
		{
			MethodName: "GetAllTimeStats",
			Handler:    _ChatService_GetAllTimeStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chat/chat.proto",
}
