// Đây là file định nghĩa giao diện (interface) của dịch vụ CHAT theo định dạng Protocol Buffers
//(proto3). File này định nghĩa các message truyền tải dữ liệu giữa client và server cũng như
//service với phương thức RPC.
//protoc --go_out=. --go-grpc_out=. proto/payment/payment.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/payment/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_GetMonthlySubscriptionSummary_FullMethodName = "/payment.PaymentService/GetMonthlySubscriptionSummary"
	PaymentService_GetMonthlyPaymentsReport_FullMethodName      = "/payment.PaymentService/GetMonthlyPaymentsReport"
	PaymentService_GetOrganizationUsageSnapshot_FullMethodName  = "/payment.PaymentService/GetOrganizationUsageSnapshot"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	// RPC kiểu unary (client gửi 1 request và nhận 1 response)
	GetMonthlySubscriptionSummary(ctx context.Context, in *GetMonthlySubscriptionSummaryRequest, opts ...grpc.CallOption) (*GetMonthlySubscriptionSummaryResponse, error)
	GetMonthlyPaymentsReport(ctx context.Context, in *GetMonthlyPaymentsReportRequest, opts ...grpc.CallOption) (*GetMonthlyPaymentsReportResponse, error)
	GetOrganizationUsageSnapshot(ctx context.Context, in *GetOrganizationUsageSnapshotRequest, opts ...grpc.CallOption) (*GetOrganizationUsageSnapshotResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) GetMonthlySubscriptionSummary(ctx context.Context, in *GetMonthlySubscriptionSummaryRequest, opts ...grpc.CallOption) (*GetMonthlySubscriptionSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthlySubscriptionSummaryResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetMonthlySubscriptionSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetMonthlyPaymentsReport(ctx context.Context, in *GetMonthlyPaymentsReportRequest, opts ...grpc.CallOption) (*GetMonthlyPaymentsReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthlyPaymentsReportResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetMonthlyPaymentsReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetOrganizationUsageSnapshot(ctx context.Context, in *GetOrganizationUsageSnapshotRequest, opts ...grpc.CallOption) (*GetOrganizationUsageSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrganizationUsageSnapshotResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetOrganizationUsageSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	// RPC kiểu unary (client gửi 1 request và nhận 1 response)
	GetMonthlySubscriptionSummary(context.Context, *GetMonthlySubscriptionSummaryRequest) (*GetMonthlySubscriptionSummaryResponse, error)
	GetMonthlyPaymentsReport(context.Context, *GetMonthlyPaymentsReportRequest) (*GetMonthlyPaymentsReportResponse, error)
	GetOrganizationUsageSnapshot(context.Context, *GetOrganizationUsageSnapshotRequest) (*GetOrganizationUsageSnapshotResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) GetMonthlySubscriptionSummary(context.Context, *GetMonthlySubscriptionSummaryRequest) (*GetMonthlySubscriptionSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlySubscriptionSummary not implemented")
}
func (UnimplementedPaymentServiceServer) GetMonthlyPaymentsReport(context.Context, *GetMonthlyPaymentsReportRequest) (*GetMonthlyPaymentsReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyPaymentsReport not implemented")
}
func (UnimplementedPaymentServiceServer) GetOrganizationUsageSnapshot(context.Context, *GetOrganizationUsageSnapshotRequest) (*GetOrganizationUsageSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizationUsageSnapshot not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_GetMonthlySubscriptionSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthlySubscriptionSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetMonthlySubscriptionSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetMonthlySubscriptionSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetMonthlySubscriptionSummary(ctx, req.(*GetMonthlySubscriptionSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetMonthlyPaymentsReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthlyPaymentsReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetMonthlyPaymentsReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetMonthlyPaymentsReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetMonthlyPaymentsReport(ctx, req.(*GetMonthlyPaymentsReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetOrganizationUsageSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizationUsageSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetOrganizationUsageSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetOrganizationUsageSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetOrganizationUsageSnapshot(ctx, req.(*GetOrganizationUsageSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonthlySubscriptionSummary",
			Handler:    _PaymentService_GetMonthlySubscriptionSummary_Handler,
		},
		{
			MethodName: "GetMonthlyPaymentsReport",
			Handler:    _PaymentService_GetMonthlyPaymentsReport_Handler,
		},
		{
			MethodName: "GetOrganizationUsageSnapshot",
			Handler:    _PaymentService_GetOrganizationUsageSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/payment/payment.proto",
}
