// Đây là file định nghĩa giao diện (interface) của dịch vụ CHAT theo định dạng Protocol Buffers
//(proto3). File này định nghĩa các message truyền tải dữ liệu giữa client và server cũng như
//service với phương thức RPC.
//protoc --go_out=. --go-grpc_out=. proto/payment/payment.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMonthlySubscriptionSummaryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	MonthExact     string                 `protobuf:"bytes,2,opt,name=month_exact,json=monthExact,proto3" json:"month_exact,omitempty"` // format: "2024-05"
	MonthGte       string                 `protobuf:"bytes,3,opt,name=month_gte,json=monthGte,proto3" json:"month_gte,omitempty"`
	MonthLte       string                 `protobuf:"bytes,4,opt,name=month_lte,json=monthLte,proto3" json:"month_lte,omitempty"`
	Ordering       string                 `protobuf:"bytes,5,opt,name=ordering,proto3" json:"ordering,omitempty"`                  // default: "-month"
	Page           int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`                         // default: 1
	PageSize       int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // default: 20
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMonthlySubscriptionSummaryRequest) Reset() {
	*x = GetMonthlySubscriptionSummaryRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlySubscriptionSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlySubscriptionSummaryRequest) ProtoMessage() {}

func (x *GetMonthlySubscriptionSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlySubscriptionSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlySubscriptionSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *GetMonthlySubscriptionSummaryRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetMonthlySubscriptionSummaryRequest) GetMonthExact() string {
	if x != nil {
		return x.MonthExact
	}
	return ""
}

func (x *GetMonthlySubscriptionSummaryRequest) GetMonthGte() string {
	if x != nil {
		return x.MonthGte
	}
	return ""
}

func (x *GetMonthlySubscriptionSummaryRequest) GetMonthLte() string {
	if x != nil {
		return x.MonthLte
	}
	return ""
}

func (x *GetMonthlySubscriptionSummaryRequest) GetOrdering() string {
	if x != nil {
		return x.Ordering
	}
	return ""
}

func (x *GetMonthlySubscriptionSummaryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMonthlySubscriptionSummaryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMonthlySubscriptionSummaryResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Count         int32                             `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Next          string                            `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previos       string                            `protobuf:"bytes,3,opt,name=previos,proto3" json:"previos,omitempty"`
	Results       []*MonthlySubscriptionSummaryItem `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlySubscriptionSummaryResponse) Reset() {
	*x = GetMonthlySubscriptionSummaryResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlySubscriptionSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlySubscriptionSummaryResponse) ProtoMessage() {}

func (x *GetMonthlySubscriptionSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlySubscriptionSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetMonthlySubscriptionSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *GetMonthlySubscriptionSummaryResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetMonthlySubscriptionSummaryResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *GetMonthlySubscriptionSummaryResponse) GetPrevios() string {
	if x != nil {
		return x.Previos
	}
	return ""
}

func (x *GetMonthlySubscriptionSummaryResponse) GetResults() []*MonthlySubscriptionSummaryItem {
	if x != nil {
		return x.Results
	}
	return nil
}

type MonthlySubscriptionSummaryItem struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Month                     string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"` // YYYY-MM-01 format
	NewSubscriptionsThisMonth int32                  `protobuf:"varint,2,opt,name=new_subscriptions_this_month,json=newSubscriptionsThisMonth,proto3" json:"new_subscriptions_this_month,omitempty"`
	ActiveSubscriptions       int32                  `protobuf:"varint,3,opt,name=active_subscriptions,json=activeSubscriptions,proto3" json:"active_subscriptions,omitempty"`
	TrialSubscriptions        int32                  `protobuf:"varint,4,opt,name=trial_subscriptions,json=trialSubscriptions,proto3" json:"trial_subscriptions,omitempty"`
	CanceledSubscriptions     int32                  `protobuf:"varint,5,opt,name=canceled_subscriptions,json=canceledSubscriptions,proto3" json:"canceled_subscriptions,omitempty"`
	MonthlyRevenue            float64                `protobuf:"fixed64,6,opt,name=monthly_revenue,json=monthlyRevenue,proto3" json:"monthly_revenue,omitempty"`
	TrialConversionRate       float64                `protobuf:"fixed64,7,opt,name=trial_conversion_rate,json=trialConversionRate,proto3" json:"trial_conversion_rate,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MonthlySubscriptionSummaryItem) Reset() {
	*x = MonthlySubscriptionSummaryItem{}
	mi := &file_proto_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlySubscriptionSummaryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlySubscriptionSummaryItem) ProtoMessage() {}

func (x *MonthlySubscriptionSummaryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlySubscriptionSummaryItem.ProtoReflect.Descriptor instead.
func (*MonthlySubscriptionSummaryItem) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *MonthlySubscriptionSummaryItem) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlySubscriptionSummaryItem) GetNewSubscriptionsThisMonth() int32 {
	if x != nil {
		return x.NewSubscriptionsThisMonth
	}
	return 0
}

func (x *MonthlySubscriptionSummaryItem) GetActiveSubscriptions() int32 {
	if x != nil {
		return x.ActiveSubscriptions
	}
	return 0
}

func (x *MonthlySubscriptionSummaryItem) GetTrialSubscriptions() int32 {
	if x != nil {
		return x.TrialSubscriptions
	}
	return 0
}

func (x *MonthlySubscriptionSummaryItem) GetCanceledSubscriptions() int32 {
	if x != nil {
		return x.CanceledSubscriptions
	}
	return 0
}

func (x *MonthlySubscriptionSummaryItem) GetMonthlyRevenue() float64 {
	if x != nil {
		return x.MonthlyRevenue
	}
	return 0
}

func (x *MonthlySubscriptionSummaryItem) GetTrialConversionRate() float64 {
	if x != nil {
		return x.TrialConversionRate
	}
	return 0
}

type GetMonthlyPaymentsReportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	MonthExact     string                 `protobuf:"bytes,2,opt,name=month_exact,json=monthExact,proto3" json:"month_exact,omitempty"`
	MonthGte       string                 `protobuf:"bytes,3,opt,name=month_gte,json=monthGte,proto3" json:"month_gte,omitempty"`
	MonthLte       string                 `protobuf:"bytes,4,opt,name=month_lte,json=monthLte,proto3" json:"month_lte,omitempty"`
	Ordering       string                 `protobuf:"bytes,5,opt,name=ordering,proto3" json:"ordering,omitempty"` // e.g., "-month"
	Page           int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMonthlyPaymentsReportRequest) Reset() {
	*x = GetMonthlyPaymentsReportRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyPaymentsReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyPaymentsReportRequest) ProtoMessage() {}

func (x *GetMonthlyPaymentsReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyPaymentsReportRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlyPaymentsReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetMonthlyPaymentsReportRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetMonthlyPaymentsReportRequest) GetMonthExact() string {
	if x != nil {
		return x.MonthExact
	}
	return ""
}

func (x *GetMonthlyPaymentsReportRequest) GetMonthGte() string {
	if x != nil {
		return x.MonthGte
	}
	return ""
}

func (x *GetMonthlyPaymentsReportRequest) GetMonthLte() string {
	if x != nil {
		return x.MonthLte
	}
	return ""
}

func (x *GetMonthlyPaymentsReportRequest) GetOrdering() string {
	if x != nil {
		return x.Ordering
	}
	return ""
}

func (x *GetMonthlyPaymentsReportRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMonthlyPaymentsReportRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type MonthlyPaymentsReportItem struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Month                     string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"` // "YYYY-MM-01"
	TotalPayments             int32                  `protobuf:"varint,2,opt,name=total_payments,json=totalPayments,proto3" json:"total_payments,omitempty"`
	TotalAmount               int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	SubscriptionPayments      int32                  `protobuf:"varint,4,opt,name=subscription_payments,json=subscriptionPayments,proto3" json:"subscription_payments,omitempty"`
	SubscriptionAmount        int64                  `protobuf:"varint,5,opt,name=subscription_amount,json=subscriptionAmount,proto3" json:"subscription_amount,omitempty"`
	AdditionalChargePayments  int32                  `protobuf:"varint,6,opt,name=additional_charge_payments,json=additionalChargePayments,proto3" json:"additional_charge_payments,omitempty"`
	AdditionalChargeAmount    int64                  `protobuf:"varint,7,opt,name=additional_charge_amount,json=additionalChargeAmount,proto3" json:"additional_charge_amount,omitempty"`
	MonthlySubscriptionAmount int64                  `protobuf:"varint,8,opt,name=monthly_subscription_amount,json=monthlySubscriptionAmount,proto3" json:"monthly_subscription_amount,omitempty"`
	YearlySubscriptionAmount  int64                  `protobuf:"varint,9,opt,name=yearly_subscription_amount,json=yearlySubscriptionAmount,proto3" json:"yearly_subscription_amount,omitempty"`
	CompletedPayments         int32                  `protobuf:"varint,10,opt,name=completed_payments,json=completedPayments,proto3" json:"completed_payments,omitempty"`
	CompletedAmount           int64                  `protobuf:"varint,11,opt,name=completed_amount,json=completedAmount,proto3" json:"completed_amount,omitempty"`
	PendingPayments           int32                  `protobuf:"varint,12,opt,name=pending_payments,json=pendingPayments,proto3" json:"pending_payments,omitempty"`
	FailedPayments            int32                  `protobuf:"varint,13,opt,name=failed_payments,json=failedPayments,proto3" json:"failed_payments,omitempty"`
	RefundedPayments          int32                  `protobuf:"varint,14,opt,name=refunded_payments,json=refundedPayments,proto3" json:"refunded_payments,omitempty"`
	PayosPaymentAmount        int64                  `protobuf:"varint,15,opt,name=payos_payment_amount,json=payosPaymentAmount,proto3" json:"payos_payment_amount,omitempty"`
	BankTransferAmount        int64                  `protobuf:"varint,16,opt,name=bank_transfer_amount,json=bankTransferAmount,proto3" json:"bank_transfer_amount,omitempty"`
	CreditCardAmount          int64                  `protobuf:"varint,17,opt,name=credit_card_amount,json=creditCardAmount,proto3" json:"credit_card_amount,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MonthlyPaymentsReportItem) Reset() {
	*x = MonthlyPaymentsReportItem{}
	mi := &file_proto_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyPaymentsReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyPaymentsReportItem) ProtoMessage() {}

func (x *MonthlyPaymentsReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyPaymentsReportItem.ProtoReflect.Descriptor instead.
func (*MonthlyPaymentsReportItem) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *MonthlyPaymentsReportItem) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyPaymentsReportItem) GetTotalPayments() int32 {
	if x != nil {
		return x.TotalPayments
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetSubscriptionPayments() int32 {
	if x != nil {
		return x.SubscriptionPayments
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetSubscriptionAmount() int64 {
	if x != nil {
		return x.SubscriptionAmount
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetAdditionalChargePayments() int32 {
	if x != nil {
		return x.AdditionalChargePayments
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetAdditionalChargeAmount() int64 {
	if x != nil {
		return x.AdditionalChargeAmount
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetMonthlySubscriptionAmount() int64 {
	if x != nil {
		return x.MonthlySubscriptionAmount
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetYearlySubscriptionAmount() int64 {
	if x != nil {
		return x.YearlySubscriptionAmount
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetCompletedPayments() int32 {
	if x != nil {
		return x.CompletedPayments
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetCompletedAmount() int64 {
	if x != nil {
		return x.CompletedAmount
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetPendingPayments() int32 {
	if x != nil {
		return x.PendingPayments
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetFailedPayments() int32 {
	if x != nil {
		return x.FailedPayments
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetRefundedPayments() int32 {
	if x != nil {
		return x.RefundedPayments
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetPayosPaymentAmount() int64 {
	if x != nil {
		return x.PayosPaymentAmount
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetBankTransferAmount() int64 {
	if x != nil {
		return x.BankTransferAmount
	}
	return 0
}

func (x *MonthlyPaymentsReportItem) GetCreditCardAmount() int64 {
	if x != nil {
		return x.CreditCardAmount
	}
	return 0
}

type GetMonthlyPaymentsReportResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Count         int32                        `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Next          string                       `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previous      string                       `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Results       []*MonthlyPaymentsReportItem `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyPaymentsReportResponse) Reset() {
	*x = GetMonthlyPaymentsReportResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyPaymentsReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyPaymentsReportResponse) ProtoMessage() {}

func (x *GetMonthlyPaymentsReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyPaymentsReportResponse.ProtoReflect.Descriptor instead.
func (*GetMonthlyPaymentsReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetMonthlyPaymentsReportResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetMonthlyPaymentsReportResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *GetMonthlyPaymentsReportResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *GetMonthlyPaymentsReportResponse) GetResults() []*MonthlyPaymentsReportItem {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetOrganizationUsageSnapshotRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizationIds []string               `protobuf:"bytes,1,rep,name=organization_ids,json=organizationIds,proto3" json:"organization_ids,omitempty"`
	Ordering        string                 `protobuf:"bytes,2,opt,name=ordering,proto3" json:"ordering,omitempty"` // "id" or "-name", etc.
	Page            int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize        int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOrganizationUsageSnapshotRequest) Reset() {
	*x = GetOrganizationUsageSnapshotRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationUsageSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationUsageSnapshotRequest) ProtoMessage() {}

func (x *GetOrganizationUsageSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationUsageSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationUsageSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrganizationUsageSnapshotRequest) GetOrganizationIds() []string {
	if x != nil {
		return x.OrganizationIds
	}
	return nil
}

func (x *GetOrganizationUsageSnapshotRequest) GetOrdering() string {
	if x != nil {
		return x.Ordering
	}
	return ""
}

func (x *GetOrganizationUsageSnapshotRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrganizationUsageSnapshotRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OrganizationUsageSnapshot struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StorageUsedMb       int32                  `protobuf:"varint,3,opt,name=storage_used_mb,json=storageUsedMb,proto3" json:"storage_used_mb,omitempty"`
	StorageLimitMb      int32                  `protobuf:"varint,4,opt,name=storage_limit_mb,json=storageLimitMb,proto3" json:"storage_limit_mb,omitempty"`
	StorageUsagePercent float32                `protobuf:"fixed32,5,opt,name=storage_usage_percent,json=storageUsagePercent,proto3" json:"storage_usage_percent,omitempty"`
	DocumentCount       int32                  `protobuf:"varint,6,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	HumanAgentCount     int32                  `protobuf:"varint,7,opt,name=human_agent_count,json=humanAgentCount,proto3" json:"human_agent_count,omitempty"`
	AiQueriesUsed       int32                  `protobuf:"varint,8,opt,name=ai_queries_used,json=aiQueriesUsed,proto3" json:"ai_queries_used,omitempty"`
	AiQueriesLimit      int32                  `protobuf:"varint,9,opt,name=ai_queries_limit,json=aiQueriesLimit,proto3" json:"ai_queries_limit,omitempty"`
	AiUsagePercent      float32                `protobuf:"fixed32,10,opt,name=ai_usage_percent,json=aiUsagePercent,proto3" json:"ai_usage_percent,omitempty"`
	SubscriptionTier    string                 `protobuf:"bytes,11,opt,name=subscription_tier,json=subscriptionTier,proto3" json:"subscription_tier,omitempty"`
	SubscriptionStatus  string                 `protobuf:"bytes,12,opt,name=subscription_status,json=subscriptionStatus,proto3" json:"subscription_status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrganizationUsageSnapshot) Reset() {
	*x = OrganizationUsageSnapshot{}
	mi := &file_proto_payment_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationUsageSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationUsageSnapshot) ProtoMessage() {}

func (x *OrganizationUsageSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationUsageSnapshot.ProtoReflect.Descriptor instead.
func (*OrganizationUsageSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{7}
}

func (x *OrganizationUsageSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationUsageSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationUsageSnapshot) GetStorageUsedMb() int32 {
	if x != nil {
		return x.StorageUsedMb
	}
	return 0
}

func (x *OrganizationUsageSnapshot) GetStorageLimitMb() int32 {
	if x != nil {
		return x.StorageLimitMb
	}
	return 0
}

func (x *OrganizationUsageSnapshot) GetStorageUsagePercent() float32 {
	if x != nil {
		return x.StorageUsagePercent
	}
	return 0
}

func (x *OrganizationUsageSnapshot) GetDocumentCount() int32 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *OrganizationUsageSnapshot) GetHumanAgentCount() int32 {
	if x != nil {
		return x.HumanAgentCount
	}
	return 0
}

func (x *OrganizationUsageSnapshot) GetAiQueriesUsed() int32 {
	if x != nil {
		return x.AiQueriesUsed
	}
	return 0
}

func (x *OrganizationUsageSnapshot) GetAiQueriesLimit() int32 {
	if x != nil {
		return x.AiQueriesLimit
	}
	return 0
}

func (x *OrganizationUsageSnapshot) GetAiUsagePercent() float32 {
	if x != nil {
		return x.AiUsagePercent
	}
	return 0
}

func (x *OrganizationUsageSnapshot) GetSubscriptionTier() string {
	if x != nil {
		return x.SubscriptionTier
	}
	return ""
}

func (x *OrganizationUsageSnapshot) GetSubscriptionStatus() string {
	if x != nil {
		return x.SubscriptionStatus
	}
	return ""
}

type GetOrganizationUsageSnapshotResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Count         int32                        `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Next          string                       `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previous      string                       `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Results       []*OrganizationUsageSnapshot `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationUsageSnapshotResponse) Reset() {
	*x = GetOrganizationUsageSnapshotResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationUsageSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationUsageSnapshotResponse) ProtoMessage() {}

func (x *GetOrganizationUsageSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationUsageSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationUsageSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrganizationUsageSnapshotResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetOrganizationUsageSnapshotResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *GetOrganizationUsageSnapshotResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *GetOrganizationUsageSnapshotResponse) GetResults() []*OrganizationUsageSnapshot {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_proto_payment_payment_proto protoreflect.FileDescriptor

const file_proto_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/payment/payment.proto\x12\apayment\"\xf7\x01\n" +
	"$GetMonthlySubscriptionSummaryRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1f\n" +
	"\vmonth_exact\x18\x02 \x01(\tR\n" +
	"monthExact\x12\x1b\n" +
	"\tmonth_gte\x18\x03 \x01(\tR\bmonthGte\x12\x1b\n" +
	"\tmonth_lte\x18\x04 \x01(\tR\bmonthLte\x12\x1a\n" +
	"\bordering\x18\x05 \x01(\tR\bordering\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"\xae\x01\n" +
	"%GetMonthlySubscriptionSummaryResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x18\n" +
	"\aprevios\x18\x03 \x01(\tR\aprevios\x12A\n" +
	"\aresults\x18\x04 \x03(\v2'.payment.MonthlySubscriptionSummaryItemR\aresults\"\xef\x02\n" +
	"\x1eMonthlySubscriptionSummaryItem\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12?\n" +
	"\x1cnew_subscriptions_this_month\x18\x02 \x01(\x05R\x19newSubscriptionsThisMonth\x121\n" +
	"\x14active_subscriptions\x18\x03 \x01(\x05R\x13activeSubscriptions\x12/\n" +
	"\x13trial_subscriptions\x18\x04 \x01(\x05R\x12trialSubscriptions\x125\n" +
	"\x16canceled_subscriptions\x18\x05 \x01(\x05R\x15canceledSubscriptions\x12'\n" +
	"\x0fmonthly_revenue\x18\x06 \x01(\x01R\x0emonthlyRevenue\x122\n" +
	"\x15trial_conversion_rate\x18\a \x01(\x01R\x13trialConversionRate\"\xf2\x01\n" +
	"\x1fGetMonthlyPaymentsReportRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1f\n" +
	"\vmonth_exact\x18\x02 \x01(\tR\n" +
	"monthExact\x12\x1b\n" +
	"\tmonth_gte\x18\x03 \x01(\tR\bmonthGte\x12\x1b\n" +
	"\tmonth_lte\x18\x04 \x01(\tR\bmonthLte\x12\x1a\n" +
	"\bordering\x18\x05 \x01(\tR\bordering\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"\xc4\x06\n" +
	"\x19MonthlyPaymentsReportItem\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12%\n" +
	"\x0etotal_payments\x18\x02 \x01(\x05R\rtotalPayments\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x123\n" +
	"\x15subscription_payments\x18\x04 \x01(\x05R\x14subscriptionPayments\x12/\n" +
	"\x13subscription_amount\x18\x05 \x01(\x03R\x12subscriptionAmount\x12<\n" +
	"\x1aadditional_charge_payments\x18\x06 \x01(\x05R\x18additionalChargePayments\x128\n" +
	"\x18additional_charge_amount\x18\a \x01(\x03R\x16additionalChargeAmount\x12>\n" +
	"\x1bmonthly_subscription_amount\x18\b \x01(\x03R\x19monthlySubscriptionAmount\x12<\n" +
	"\x1ayearly_subscription_amount\x18\t \x01(\x03R\x18yearlySubscriptionAmount\x12-\n" +
	"\x12completed_payments\x18\n" +
	" \x01(\x05R\x11completedPayments\x12)\n" +
	"\x10completed_amount\x18\v \x01(\x03R\x0fcompletedAmount\x12)\n" +
	"\x10pending_payments\x18\f \x01(\x05R\x0fpendingPayments\x12'\n" +
	"\x0ffailed_payments\x18\r \x01(\x05R\x0efailedPayments\x12+\n" +
	"\x11refunded_payments\x18\x0e \x01(\x05R\x10refundedPayments\x120\n" +
	"\x14payos_payment_amount\x18\x0f \x01(\x03R\x12payosPaymentAmount\x120\n" +
	"\x14bank_transfer_amount\x18\x10 \x01(\x03R\x12bankTransferAmount\x12,\n" +
	"\x12credit_card_amount\x18\x11 \x01(\x03R\x10creditCardAmount\"\xa6\x01\n" +
	" GetMonthlyPaymentsReportResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x03 \x01(\tR\bprevious\x12<\n" +
	"\aresults\x18\x04 \x03(\v2\".payment.MonthlyPaymentsReportItemR\aresults\"\x9d\x01\n" +
	"#GetOrganizationUsageSnapshotRequest\x12)\n" +
	"\x10organization_ids\x18\x01 \x03(\tR\x0forganizationIds\x12\x1a\n" +
	"\bordering\x18\x02 \x01(\tR\bordering\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xf2\x03\n" +
	"\x19OrganizationUsageSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0fstorage_used_mb\x18\x03 \x01(\x05R\rstorageUsedMb\x12(\n" +
	"\x10storage_limit_mb\x18\x04 \x01(\x05R\x0estorageLimitMb\x122\n" +
	"\x15storage_usage_percent\x18\x05 \x01(\x02R\x13storageUsagePercent\x12%\n" +
	"\x0edocument_count\x18\x06 \x01(\x05R\rdocumentCount\x12*\n" +
	"\x11human_agent_count\x18\a \x01(\x05R\x0fhumanAgentCount\x12&\n" +
	"\x0fai_queries_used\x18\b \x01(\x05R\raiQueriesUsed\x12(\n" +
	"\x10ai_queries_limit\x18\t \x01(\x05R\x0eaiQueriesLimit\x12(\n" +
	"\x10ai_usage_percent\x18\n" +
	" \x01(\x02R\x0eaiUsagePercent\x12+\n" +
	"\x11subscription_tier\x18\v \x01(\tR\x10subscriptionTier\x12/\n" +
	"\x13subscription_status\x18\f \x01(\tR\x12subscriptionStatus\"\xaa\x01\n" +
	"$GetOrganizationUsageSnapshotResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x03 \x01(\tR\bprevious\x12<\n" +
	"\aresults\x18\x04 \x03(\v2\".payment.OrganizationUsageSnapshotR\aresults2\x81\x03\n" +
	"\x0ePaymentService\x12\x80\x01\n" +
	"\x1dGetMonthlySubscriptionSummary\x12-.payment.GetMonthlySubscriptionSummaryRequest\x1a..payment.GetMonthlySubscriptionSummaryResponse\"\x00\x12o\n" +
	"\x18GetMonthlyPaymentsReport\x12(.payment.GetMonthlyPaymentsReportRequest\x1a).payment.GetMonthlyPaymentsReportResponse\x12{\n" +
	"\x1cGetOrganizationUsageSnapshot\x12,.payment.GetOrganizationUsageSnapshotRequest\x1a-.payment.GetOrganizationUsageSnapshotResponseB\x0fZ\rproto/paymentb\x06proto3"

var (
	file_proto_payment_payment_proto_rawDescOnce sync.Once
	file_proto_payment_payment_proto_rawDescData []byte
)

func file_proto_payment_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_payment_proto_rawDesc), len(file_proto_payment_payment_proto_rawDesc)))
	})
	return file_proto_payment_payment_proto_rawDescData
}

var file_proto_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_payment_payment_proto_goTypes = []any{
	(*GetMonthlySubscriptionSummaryRequest)(nil),  // 0: payment.GetMonthlySubscriptionSummaryRequest
	(*GetMonthlySubscriptionSummaryResponse)(nil), // 1: payment.GetMonthlySubscriptionSummaryResponse
	(*MonthlySubscriptionSummaryItem)(nil),        // 2: payment.MonthlySubscriptionSummaryItem
	(*GetMonthlyPaymentsReportRequest)(nil),       // 3: payment.GetMonthlyPaymentsReportRequest
	(*MonthlyPaymentsReportItem)(nil),             // 4: payment.MonthlyPaymentsReportItem
	(*GetMonthlyPaymentsReportResponse)(nil),      // 5: payment.GetMonthlyPaymentsReportResponse
	(*GetOrganizationUsageSnapshotRequest)(nil),   // 6: payment.GetOrganizationUsageSnapshotRequest
	(*OrganizationUsageSnapshot)(nil),             // 7: payment.OrganizationUsageSnapshot
	(*GetOrganizationUsageSnapshotResponse)(nil),  // 8: payment.GetOrganizationUsageSnapshotResponse
}
var file_proto_payment_payment_proto_depIdxs = []int32{
	2, // 0: payment.GetMonthlySubscriptionSummaryResponse.results:type_name -> payment.MonthlySubscriptionSummaryItem
	4, // 1: payment.GetMonthlyPaymentsReportResponse.results:type_name -> payment.MonthlyPaymentsReportItem
	7, // 2: payment.GetOrganizationUsageSnapshotResponse.results:type_name -> payment.OrganizationUsageSnapshot
	0, // 3: payment.PaymentService.GetMonthlySubscriptionSummary:input_type -> payment.GetMonthlySubscriptionSummaryRequest
	3, // 4: payment.PaymentService.GetMonthlyPaymentsReport:input_type -> payment.GetMonthlyPaymentsReportRequest
	6, // 5: payment.PaymentService.GetOrganizationUsageSnapshot:input_type -> payment.GetOrganizationUsageSnapshotRequest
	1, // 6: payment.PaymentService.GetMonthlySubscriptionSummary:output_type -> payment.GetMonthlySubscriptionSummaryResponse
	5, // 7: payment.PaymentService.GetMonthlyPaymentsReport:output_type -> payment.GetMonthlyPaymentsReportResponse
	8, // 8: payment.PaymentService.GetOrganizationUsageSnapshot:output_type -> payment.GetOrganizationUsageSnapshotResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_payment_payment_proto_init() }
func file_proto_payment_payment_proto_init() {
	if File_proto_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_payment_proto_rawDesc), len(file_proto_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_payment_proto_depIdxs,
		MessageInfos:      file_proto_payment_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_payment_proto = out.File
	file_proto_payment_payment_proto_goTypes = nil
	file_proto_payment_payment_proto_depIdxs = nil
}
